### ISSUE TITLE
1.5V and 5V cycle for sensors like MQ7

### ISSUE THREAD

**Issue by amirsalman93** [miguel5612/MQSensorsLib#26]
If you look at the datasheet of MQ7, It requires a periodic cycle of 5V (Release State for 60 seconds) and 1.5V (Absorb state for 90 seconds) to operate correctly. 

Source: https://www.sparkfun.com/datasheets/Sensors/Biometric/MQ-7.pdf

![image](https://user-images.githubusercontent.com/57857809/79047334-62bbbf80-7c2f-11ea-8266-f328f3800678.png)

Can you please add it to the library? 
Thanks

**Comment by miguel5612** [comment]
According to:
[https://forum.arduino.cc/index.php?topic=204036.0](Calculating PWM Duty Cycles)
> A TRMS instrument would show you sqrt(12^2*0.25) = 6V

This means, using a sqrt(5^2*0.08) = sqrt(2) = 1.4142135 -> DutyCycle **8%** is equal to **1.41 Volts** aprox
And according to:
[https://forum.arduino.cc/index.php?topic=567771.0](https://forum.arduino.cc/index.php?topic=567771.0)
Heater could be conected using a mosfet (IRLZ34N)
![image](https://user-images.githubusercontent.com/18131167/79810278-4eb34480-8338-11ea-9e60-4590777790e1.png)
**Note**: if you are going to do this practice with a nodeMCU, ESP8266 or ESP32, you must place the voltage divider at the output so that your output range reaching pin A0 of your arduino is between 0 and 3V3
Code: We will update MQ7 - MQ-309 examples.
