### ISSUE TITLE
MQ135 example all: CO2 value is not ppm?

### ISSUE THREAD

**Issue by loublock** [miguel5612/MQSensorsLib#40]
**Describe the bug**
When i run your example code it return values ca. between 401 - 410 ppm.  When you subtract the offset of 400 from this value it seems the remaining value is 100 times lower than it should be. What am I missing?

**To Reproduce**
1. run mq135 all example code
2. place hardware outside or in a room where you know the actual co2 ppm
2. look on the output window

**Expected behavior**
getting co2 values of around 400 to 1500 depends room condition

**Desktop (please complete the following information):**
 - OS: win10
- arduino nano
- mq135 (pre heated and run for 24h straight)
- vs code

**Comment by miguel5612** [comment]
This is a behavior caused by errors in the calibration, after preheating the sensor for 24 hours you must introduce it in a clean atmosphere (could be in the early morning) at that time you restart the arduino, it reads the values of R0 as clean air and then during the day you start to measure the variations of the resistance which is what will give you the real values of PPM.
