### ISSUE TITLE
Calculations for RS using mq303a sensor look wrong

### ISSUE THREAD

**Issue by colinmeikle** [miguel5612/MQSensorsLib#42]
The calculation of RS in the library assumes the load resistor is connected between GND and the sensor ( the other end of the sensor is connected to VCC) . However for the the Mq303A this is the other way round. For the MQ303a the Load resistor is connected between the sensor output and VCC (not GND like most of the other sensors)
see the connection of the test circuit here: http://www.kosmodrom.com.ua/pdf/MQ303A.pdf
So you can not use the same formula to calculate RS  i.e.   RS = [(VC x RL) / VRL] - RL  is wrong.

Also this is a 3pin sensor, the other end of the sensor appears to be connected to the mid point of the heater. I can not see this confirmed in any data sheet but from experimentation this appears to be the case (also the drawings show like this). With the heater voltage at 0.9 volts, the other end of the sensor will be at 0.45V not 0v so again this will affect the calculation  of RS and needs to be taken into account (0.45 needs to be taken off VCC?).

**Comment by miguel5612** [comment]
From Ohm’s Law, we can derive I as follows:

  I = V / R  
Which in our circuit is equal to: 

  I = VC / (RS+RL)  
Going back to our original circuit from Figure 6, we can obtain the output voltage at the load resistor using the value obtained for I and Ohm’s Law.

V = I x R 
VRL = [VC / (RS + RL)] x RL 
VRL = (VC x RL) / (RS + RL) 
So now we solve for RS: 

VRL x (RS + RL) = VC x RL
(VRL x RS) + (VRL x RL) = VC x RL 
(VRL x RS) = (VC x RL) - (VRL x RL)
RS = [(VC x RL) - (VRL x RL)] / VRL
RS = [(VC x RL) / VRL] - RL

Taking into account that given the position of Rs from now on we can assume VC as VC - 0.45 and that as a voltage divider even if we change the resistors position (RS against GND and RL against VCC) the voltages remain the same because the ratios are maintained, the only adjustment to be made is that VC is now VC - 0.45.
