### ISSUE TITLE
Conflicted MQsensor library with ThinkSpeak library.

### ISSUE THREAD

**Issue by Adhitya-02** [miguel5612/MQSensorsLib#65]
I think there is a conflict that occurs between this MQ library and the ThingSpeak library, after pre-heating the sensor always displays a Warning message: Connection issue, R0 is infinite (Open circuit detected) please check your wiring and supply, but if I do not include the ThingSpeak communication program the sensor readings can be seen properly. This is just my assumption, what do you guys think?

**Comment by miguel5612** [comment]
Hi,

It's possible that there might be a conflict between the MQ sensor library and the ThingSpeak library. However, it's also possible that there could be other issues at play.

One issue could be related to power management. The ESP board might not be able to supply enough power to both the MQ sensor and the WiFi module at the same time, especially during the pre-heating phase of the MQ sensor, which could lead to instability.

Another potential issue could be related to the execution order or timing in your code. The MQ sensor needs to preheat and stabilize before it can provide valid readings. If the ThingSpeak library or related code is executed during this pre-heating period, it might interrupt or otherwise affect the MQ sensor's operation.

Without seeing your code, it's difficult to say for certain what the issue might be. However, I would recommend:

Check your power supply. Make sure it can provide sufficient power to your ESP board, MQ sensor, and any other connected peripherals.
Experiment with the timing and order of execution in your code. Make sure the MQ sensor has sufficient time to preheat and stabilize before any other major operations (like establishing a WiFi connection or sending data to ThingSpeak) are performed.
Try using a simple test program to isolate and identify the issue. For example, a program that only initializes the MQ sensor and reads its values, with no ThingSpeak or WiFi code.
Check your wiring and connections again, as the error suggests a connection issue. Make sure that there is a stable connection between the ESP board and the sensor.
Hope this helps! Let us know if you have any other questions or if there's more information you can provide.
